buildscript {
  allprojects {
    apply from: "$rootDir/../gradle/common.gradle"

    buildscript {
      repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
      }

      dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "com.android.tools.build:gradle:$androidToolsVersion"
        classpath "com.vanniktech:gradle-maven-publish-plugin:$mavenPublishVersion"
        classpath "com.gradleup.shadow:shadow-gradle-plugin:$shadowVersion"
      }
    }

    repositories {
      google()
      mavenCentral()
    }
  }
}

apply plugin: 'org.jetbrains.kotlin.jvm'

sourceSets {
  functionalTest {
    java {
      compileClasspath += main.output
      runtimeClasspath += main.output
    }
  }
}

dependencies {
  functionalTestImplementation gradleTestKit()
  functionalTestImplementation "junit:junit:$junitVersion"
}

tasks.register("functionalTest", Test.class) {
  description = "Runs functional tests."
  group = "verification"

  testClassesDirs = project.sourceSets.functionalTest.output.classesDirs
  classpath = project.sourceSets.functionalTest.runtimeClasspath
  systemProperty "lightsaber.version", project.version
  systemProperty "kotlin.version", kotlinVersion
  systemProperty "android.tools.version", androidToolsVersion
  systemProperty "android.compile.sdk.version", androidCompileSdkVersion
}

afterEvaluate {
  tasks.named("functionalTest") {
    subprojects.each {
      dependsOn(it.tasks.named("publishToMavenLocal"))
    }
  }
}
