name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default]
        arch: [x86_64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Publish bootstrap artifacts
        run: ./gradlew publishToMavenLocal -Pbootstrap=true --no-daemon

      - name: Run unit tests
        run: ./gradlew check --no-daemon

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: |
            ./gradlew connectedCheck --no-daemon
      - name: Publish to Bintray
        if: contains(github.ref, '/tags/v')
        run: |
          ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_USER }} -PbintrayKey=${{ secrets.BINTRAY_KEY }}
